### ISSUE TITLE
Can't swap when special tokens

### ISSUE THREAD

**Issue by winer328** [Allen-Taylor/raydium_py#2]
Hi, Thanks for your full code for swap.
I implemented swap in node.js with Raydium sdk and it worked well.
I found python swap code in raydium here and I cloned it.
But when I want swap with `SHDWyBxihqiCj6YekG2GUr7wqKLeLAMK1gHZck9pL6y`, No pools keys found... error occurs.
When I swap in node.js, it works well.
What's the issue in this?

**Comment by Allen-Taylor** [comment]
Try putting in the pair address directly: 

2wbnvtStBTRRGJhCAwpLSWxrUrfRL4H2FTsujseALsm1

You are using the mint address. 

This one has multiple pools from Raydium, Orca, etc.

**Comment by winer328** [comment]
Thanks, @Allen-Taylor 
You are really good dev.
