### ISSUE TITLE
no pool keys found by free rpc

### ISSUE THREAD

**Issue by HiiroAyane** [Allen-Taylor/raydium_py#3]
Starting buy transaction for pair address: 5gtpkvs7Yrj2CX8L7eDVamBbAQoJHtZjSu7q96UhjJ5U
Fetching pool keys...
Error occurred: 
No pool keys found...

is this error caused by free rpc?
If I buy rpc from helius or quickNode, which plan should I select?
thanks a lot.

**Comment by Allen-Taylor** [comment]
Depends on what your goal is. The more you spend the quicker your transaction will be processed.

**Comment by HiiroAyane** [comment]
> Depends on what your goal is. The more you spend the quicker your transaction will be processed.

I understand. And is this issue caused by free rpc ?(No pool keys found)

**Comment by Allen-Taylor** [comment]
Yeah the free RPCs don't have access to all the RPC endpoints. In the code, we are fetching the pool keys from the blockchain. 

Check out my jupiter-py repo, that should work with a free RPC. You have a very low chance of landing a transaction though on free tiers.

**Comment by HiiroAyane** [comment]
> Yeah the free RPCs don't have access to all the RPC endpoints. In the code, we are fetching the pool keys from the blockchain.
> 
> Check out my jupiter-py repo, that should work with a free RPC. You have a very low chance of landing a transaction though on free tiers.

thanks a lot.

**Comment by HiiroAyane** [comment]
> Yeah the free RPCs don't have access to all the RPC endpoints. In the code, we are fetching the pool keys from the blockchain.
> 
> Check out my jupiter-py repo, that should work with a free RPC. You have a very low chance of landing a transaction though on free tiers.

as I used helius dev plan, and I set RPC="https://api.helius.xyz/transactions?api-key=xxx" in config.py, it's still have No pool keys found Error

is my config RPC set wrong?
or there have another miss I have made? token address is 68JKPf1pCDGxJDwJtwMZ3v4osYx62EF5xgh7NgXjKBxR

**Comment by HiiroAyane** [comment]
detail error msg below
Starting buy transaction for pair address: 5gtpkvs7Yrj2CX8L7eDVamBbAQoJHtZjSu7q96UhjJ5U
Fetching pool keys...
Error occurred: data did not match any variant of untagged enum Resp
No pool keys found...

**Comment by HiiroAyane** [comment]
> Yeah the free RPCs don't have access to all the RPC endpoints. In the code, we are fetching the pool keys from the blockchain.
> 
> Check out my jupiter-py repo, that should work with a free RPC. You have a very low chance of landing a transaction though on free tiers.

I used new RPC and log like this
Transaction Signature: 648geGmneK2ikC43dfDPfbY8x26cUZokuw7JCG1t5kGNZBHGi37LsPRGi7sGcAGz3E72mXZGf4Unu1d2zoNYSDLL
Confirming transaction...
Awaiting confirmation... try count: 1
Awaiting confirmation... try count: 2
Error: Transaction not confirmed. Retrying...
Transaction failed.
Transaction confirmed: False

I find on solscan it error like this
Fail
- finalized (MAX confirmations)
Program Error: "Instruction #5 Failed - Unknown instruction error"

and my 
sol_in = 0.01
slippage = 5

what could cause the confirm failed questions?
