### ISSUE TITLE
some specific token could not sell...

### ISSUE THREAD

**Issue by HiiroAyane** [Allen-Taylor/raydium_py#4]
Here is the error on solscan:
Program Error: "Instruction #7 Failed - custom program error: Non-native account can only be closed if its balance is zero"
Program logs:
#7 Token Program instruction
> Program log: Instruction: CloseAccount
> Program log: Error: Non-native account can only be closed if its balance is zero
> Program[ Token Program ](https://solscan.io/account/TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA)consumed 2677 of 60826 compute units
> Program returned error: custom program error: 0xb

but I read the code and only when sell percent == 100% can close the token account...
how could it happen...

toekn addr is 25x9Av7ddPJQFVJy512VzzQ96A2Tqza22LtfHTKCpump

**Comment by Allen-Taylor** [comment]
Hey man, it looks like a math rounding error in the token amount. You can only close the token account if you have a zero token balance. 

Try to sell 99% of the tokens.

**Comment by HiiroAyane** [comment]
maybe 

> Hey man, it looks like a math rounding error in the token amount. You can only close the token account if you have a zero token balance.
> 
> Try to sell 99% of the tokens.

yes... I added

        if percentage == 100:
            percentage = 99.99

at raydium.py line 155

**Comment by HiiroAyane** [comment]
> Hey man, it looks like a math rounding error in the token amount. You can only close the token account if you have a zero token balance.
> 
> Try to sell 99% of the tokens.

yes... I added

    if percentage == 100:
        percentage = 99.99

at raydium.py line 155

**Comment by Allen-Taylor** [comment]
That isn't what I meant.

I meant when you sell the token, put 99 not 100. It only tries to close the token account if you put 100. Remove the change you made bc it makes no sense.
